id: ABFC9FDDF
title: 'A Lament of Faith: A Short Remembrance of, and Prayer to, My Guru, the Wish-Fulfilling
  Jewel'
type: translation
pechas:
- I8933D42C
- I84AB08FA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:58.691917
  last_modified_at: 2023-01-04 12:49:58.691932
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I8933D42C/0417: A55E
  I84AB08FA/F249: A55E
